#include <stdio.h>

int yyerror_isinitialized, yymaxstate = 182;
struct errtable {
   int i;
   union {
      char *msg;
      struct errtable *p;
      } u;
   } errtab[183];
int yyerror_init()
{
   errtab[89].i = 2;
   errtab[89].u.p = calloc(1,3 * sizeof(struct errtable));
   errtab[89].u.p[0].u.msg = "Missing type in formal in method declaration";
   errtab[89].u.p[1].i = 277;
   errtab[89].u.p[1].u.msg = "Wrong type in formal in method declaration";
   errtab[89].u.p[2].i = 283;
   errtab[89].u.p[2].u.msg = "Missing type in formal in method declaration";
   errtab[94].i = 2;
   errtab[94].u.p = calloc(1,3 * sizeof(struct errtable));
   errtab[94].u.p[0].u.msg = "Missing ';' at the end of field declaration";
   errtab[94].u.p[1].i = 282;
   errtab[94].u.p[1].u.msg = "Missing ';' at the end of field declaration";
   errtab[94].u.p[2].i = 278;
   errtab[94].u.p[2].u.msg = "Missing '<-' in assignment";
   errtab[136].i = 1;
   errtab[136].u.msg = "Missing right member in '-' expression";
   errtab[178].i = 1;
   errtab[178].u.msg = "Missing 'in' in let declaration";
   errtab[141].i = 1;
   errtab[141].u.msg = "Missing right member in '=' expression";
   errtab[146].i = 1;
   errtab[146].u.msg = "Unexpected ';' at the end fof block";
   errtab[62].i = 1;
   errtab[62].u.msg = "Extension can only be applied on objects";
   errtab[83].i = 5;
   errtab[83].u.p = calloc(1,6 * sizeof(struct errtable));
   errtab[83].u.p[0].u.msg = "Missing closing brackets in method declaration";
   errtab[83].u.p[1].i = 277;
   errtab[83].u.p[1].u.msg = "Missing ',' to separate formals in method declaration";
   errtab[83].u.p[2].i = 285;
   errtab[83].u.p[2].u.msg = "Missing name in formal in method declaration";
   errtab[83].u.p[3].i = 279;
   errtab[83].u.p[3].u.msg = "Formal name cannot start with a capital letter";
   errtab[83].u.p[4].i = 284;
   errtab[83].u.p[4].u.msg = "Too many opening brackets in method declaration";
   errtab[83].u.p[5].i = 286;
   errtab[83].u.p[5].u.msg = "Wrong separator of formals in method declaration";
   errtab[109].i = 1;
   errtab[109].u.msg = "Missing expression after 'if'";
   errtab[130].i = 2;
   errtab[130].u.p = calloc(1,3 * sizeof(struct errtable));
   errtab[130].u.p[0].u.msg = "Missing 'then' after 'if'";
   errtab[130].u.p[1].i = 282;
   errtab[130].u.p[1].u.msg = "Missing 'then' after 'if'";
   errtab[130].u.p[2].i = 278;
   errtab[130].u.p[2].u.msg = "Missing 'then' after 'if'";
   errtab[135].i = 1;
   errtab[135].u.msg = "Missing right member in '+' expression";
   errtab[177].i = 1;
   errtab[177].u.msg = "Missing expression after 'then'";
   errtab[182].i = 1;
   errtab[182].u.msg = "Missing expression after 'in' in let declaration";
   errtab[119].i = 2;
   errtab[119].u.p = calloc(1,3 * sizeof(struct errtable));
   errtab[119].u.p[0].u.msg = "Missing type in method declaration";
   errtab[119].u.p[1].i = 277;
   errtab[119].u.p[1].u.msg = "Wrong type in method declaration";
   errtab[119].u.p[2].i = 281;
   errtab[119].u.p[2].u.msg = "Missing type in method declaration";
   errtab[82].i = 1;
   errtab[82].u.msg = "Missing ':' in formal in method declaration";
   errtab[129].i = 1;
   errtab[129].u.msg = "Missing value to assign in assignment";
   errtab[150].i = 2;
   errtab[150].u.p = calloc(1,3 * sizeof(struct errtable));
   errtab[150].u.p[0].u.msg = "Missing closing brackets at the end of call";
   errtab[150].u.p[1].i = 282;
   errtab[150].u.p[1].u.msg = "Missing closing brackets at the end of call";
   errtab[150].u.p[2].i = 287;
   errtab[150].u.p[2].u.msg = "Unexpected ',' in function call";
   errtab[66].i = 5;
   errtab[66].u.p = calloc(1,6 * sizeof(struct errtable));
   errtab[66].u.p[0].u.msg = "Missing closing curly brace at the end of class";
   errtab[66].u.p[1].i = 0;
   errtab[66].u.p[1].u.msg = "Missing closing curly brace at the end of class";
   errtab[66].u.p[2].i = 285;
   errtab[66].u.p[2].u.msg = "Missing name in field declaration";
   errtab[66].u.p[3].i = 279;
   errtab[66].u.p[3].u.msg = "Method cannot start with a capital letter";
   errtab[66].u.p[4].i = 284;
   errtab[66].u.p[4].u.msg = "Missing method name in method declaration";
   errtab[66].u.p[5].i = 281;
   errtab[66].u.p[5].u.msg = "Too much opening curly braces at the beginning of class";
   errtab[87].i = 2;
   errtab[87].u.p = calloc(1,3 * sizeof(struct errtable));
   errtab[87].u.p[0].u.msg = "Mising assignemen value";
   errtab[87].u.p[1].i = 266;
   errtab[87].u.p[1].u.msg = "Missing expression after '<-' in let declaration";
   errtab[87].u.p[2].i = 286;
   errtab[87].u.p[2].u.msg = "Mising assignemen value";
   errtab[134].i = 1;
   errtab[134].u.msg = "Missing right member in 'and' expression";
   errtab[8].i = 2;
   errtab[8].u.p = calloc(1,3 * sizeof(struct errtable));
   errtab[8].u.p[0].u.msg = "Missing class name";
   errtab[8].u.p[1].i = 277;
   errtab[8].u.p[1].u.msg = "First letter of class is not uppercase";
   errtab[8].u.p[2].i = 281;
   errtab[8].u.p[2].u.msg = "Missing class name";
   errtab[97].i = 1;
   errtab[97].u.msg = "Missing expression after 'isnull'";
   errtab[139].i = 1;
   errtab[139].u.msg = "Missing right member in '^' expression";
   errtab[144].i = 1;
   errtab[144].u.msg = "Missing opening curly braces in method declaration";
   errtab[91].i = 1;
   errtab[91].u.msg = "Unexpected ',' after formal in method declaration";
   errtab[112].i = 1;
   errtab[112].u.msg = "Missing expression after 'new'";
   errtab[154].i = 2;
   errtab[154].u.p = calloc(1,3 * sizeof(struct errtable));
   errtab[154].u.p[0].u.msg = "Missing type in let declaration";
   errtab[154].u.p[1].i = 277;
   errtab[154].u.p[1].u.msg = "Invalid type in let declaration";
   errtab[154].u.p[2].i = 266;
   errtab[154].u.p[2].u.msg = "Missing type in let declaration";
   errtab[70].i = 1;
   errtab[70].u.msg = "Missing ':' in field declaration";
   errtab[75].i = 2;
   errtab[75].u.p = calloc(1,3 * sizeof(struct errtable));
   errtab[75].u.p[0].u.msg = "Missing type in field declaration";
   errtab[75].u.p[1].i = 277;
   errtab[75].u.p[1].u.msg = "Wrong type in field declaration";
   errtab[75].u.p[2].i = 286;
   errtab[75].u.p[2].u.msg = "Missing type in field declaration";
   errtab[138].i = 1;
   errtab[138].u.msg = "Missing right member in '/' expression";
   errtab[143].i = 1;
   errtab[143].u.msg = "Missing right member in '<=' expression";
   errtab[90].i = 3;
   errtab[90].u.p = calloc(1,4 * sizeof(struct errtable));
   errtab[90].u.p[0].u.msg = "Missing ':' in method declaration";
   errtab[90].u.p[1].i = 267;
   errtab[90].u.p[1].u.msg = "Missing ':' in method declaration";
   errtab[90].u.p[2].i = 286;
   errtab[90].u.p[2].u.msg = "Wrong separator in method declaration";
   errtab[90].u.p[3].i = 283;
   errtab[90].u.p[3].u.msg = "Too many closing brackets in method declaration";
   errtab[111].i = 2;
   errtab[111].u.p = calloc(1,3 * sizeof(struct errtable));
   errtab[111].u.p[0].u.msg = "Missing variable name in let declaration";
   errtab[111].u.p[1].i = 285;
   errtab[111].u.p[1].u.msg = "Missing variable name in let declaration";
   errtab[111].u.p[2].i = 279;
   errtab[111].u.p[2].u.msg = "Variable name can not start with a capital letter in let declaration";
   errtab[132].i = 2;
   errtab[132].u.p = calloc(1,3 * sizeof(struct errtable));
   errtab[132].u.p[0].u.msg = "Missing ':' in let declaration";
   errtab[132].u.p[1].i = 267;
   errtab[132].u.p[1].u.msg = "Missing ':' in let declaration";
   errtab[132].u.p[2].i = 286;
   errtab[132].u.p[2].u.msg = "Wrong separator in let declaration";
   errtab[153].i = 1;
   errtab[153].u.msg = "Missing expression after 'do'";
   errtab[6].i = 2;
   errtab[6].u.p = calloc(1,3 * sizeof(struct errtable));
   errtab[6].u.p[0].u.msg = "The program should contain at least one class";
   errtab[6].u.p[1].i = 0;
   errtab[6].u.p[1].u.msg = "The program should contain at least one class";
   errtab[6].u.p[2].i = 279;
   errtab[6].u.p[2].u.msg = "Wrong class definition keyword, should be 'class'";
   errtab[137].i = 1;
   errtab[137].u.msg = "Missing right member in '*' expression";
   errtab[100].i = 1;
   errtab[100].u.msg = "Missing expression after 'not'";
   errtab[126].i = 1;
   errtab[126].u.msg = "Missing closing brackets";
   errtab[142].i = 1;
   errtab[142].u.msg = "Missing right member in '<' expression";
   errtab[147].i = 4;
   errtab[147].u.p = calloc(1,5 * sizeof(struct errtable));
   errtab[147].u.p[0].u.msg = "Missing ';' at the end of expression";
   errtab[147].u.p[1].i = 285;
   errtab[147].u.p[1].u.msg = "Wrong separator in function call";
   errtab[147].u.p[2].i = 287;
   errtab[147].u.p[2].u.msg = "Wrong expression separator in block";
   errtab[147].u.p[3].i = 278;
   errtab[147].u.p[3].u.msg = "Missing ';' at the end of expression";
   errtab[147].u.p[4].i = 283;
   errtab[147].u.p[4].u.msg = "Too many closing brackets";
   errtab[168].i = 1;
   errtab[168].u.msg = "Unexpected ',' in function call";
   errtab[63].i = 3;
   errtab[63].u.p = calloc(1,4 * sizeof(struct errtable));
   errtab[63].u.p[0].u.msg = "Missing opening curly brace at the beginning of class";
   errtab[63].u.p[1].i = 277;
   errtab[63].u.p[1].u.msg = "Wrong extension keyword, use 'extends'";
   errtab[63].u.p[2].i = 282;
   errtab[63].u.p[2].u.msg = "Missing opening curly brace at the beginning of class";
   errtab[63].u.p[3].i = 279;
   errtab[63].u.p[3].u.msg = "Missing extension keyword";
   errtab[105].i = 13;
   errtab[105].u.p = calloc(1,14 * sizeof(struct errtable));
   errtab[105].u.p[0].u.msg = "Mising opening brackets in method declaration";
   errtab[105].u.p[1].i = 290;
   errtab[105].u.p[1].u.msg = "Missing left member in '*' expression";
   errtab[105].u.p[2].i = 261;
   errtab[105].u.p[2].u.msg = "Missing 'while' before 'do'";
   errtab[105].u.p[3].i = 282;
   errtab[105].u.p[3].u.msg = "Block must contain at least one expression";
   errtab[105].u.p[4].i = 295;
   errtab[105].u.p[4].u.msg = "Missing left member in '<' expression";
   errtab[105].u.p[5].i = 258;
   errtab[105].u.p[5].u.msg = "Missing left member in 'and' expression";
   errtab[105].u.p[6].i = 279;
   errtab[105].u.p[6].u.msg = "Function call cannot start with a capital letter";
   errtab[105].u.p[7].i = 292;
   errtab[105].u.p[7].u.msg = "Missing left member in '^' expression";
   errtab[105].u.p[8].i = 297;
   errtab[105].u.p[8].u.msg = "Missing assignee in assignment";
   errtab[105].u.p[9].i = 273;
   errtab[105].u.p[9].u.msg = "Missing 'if' before 'then'";
   errtab[105].u.p[10].i = 294;
   errtab[105].u.p[10].u.msg = "Missing left member in '=' expression";
   errtab[105].u.p[11].i = 291;
   errtab[105].u.p[11].u.msg = "Missing left member in '/' expression";
   errtab[105].u.p[12].i = 288;
   errtab[105].u.p[12].u.msg = "Missing left member in '+' expression";
   errtab[105].u.p[13].i = 296;
   errtab[105].u.p[13].u.msg = "Missing left member in '<=' expression";
   errtab[110].i = 1;
   errtab[110].u.msg = "Missing expression after 'while'";
   errtab[131].i = 1;
   errtab[131].u.msg = "Missing 'do' after 'while'";
   errtab[152].i = 1;
   errtab[152].u.msg = "Missing expression after 'else'";
}

extern int errors;
extern char *yyfilename, yytext[];
extern int yychar, yylineno;

extern short *yyssp;

int yyerror(char *s)
{
   int state = *yyssp;
   int i;
   char sbuf[128];
   if (! yyerror_isinitialized++) yyerror_init();
   if (strstr(s, "stack")) return 0;
   if (errors++ > 10) {
      fprintf(stderr, "too many errors, aborting");
      exit(errors); }
   if(yyfilename) fprintf(stderr, "%s:", yyfilename);
   if ((!strcmp(s, "syntax error") || !strcmp(s,"parse error"))&&
         (state>=0 && state<=yymaxstate))
       if (errtab[state].i==1)
         s = errtab[state].u.msg;
       else {
          for(i=1;i<=errtab[state].i;i++)
             if(yychar == errtab[state].u.p[i].i) {
                s=errtab[state].u.p[i].u.msg;break;}
          if(i>errtab[state].i)s=errtab[state].u.p[0].u.msg;
          }
   if (!strcmp(s, "syntax error") || !strcmp(s,"parse error")){
      sprintf(sbuf,"%s (%d;%d)", s, state, yychar);
      s=sbuf;
      }
   fprintf(stderr, "%d: # \"%s\": %s\n", yylineno, yytext, s);
   return 0;
}
